#!/bin/bash

SCRIPT_COMMON_FILE=/usr/local/rak/shell_script/rak_common.sh
source $SCRIPT_COMMON_FILE

GW_MODEL=`do_get_gw_model`
LORA_SPI=`do_get_lora_spi`


do_get_mac()
{
    GATEWAY_EUI_NIC="eth0"
    if [[ `grep "$GATEWAY_EUI_NIC" /proc/net/dev` == "" ]]; then
        GATEWAY_EUI_NIC="wlan0"
    fi
        if [[ `grep "$GATEWAY_EUI_NIC" /proc/net/dev` == "" ]]; then
        GATEWAY_EUI_NIC="usb0"
    fi

    if [[ `grep "$GATEWAY_EUI_NIC" /proc/net/dev` == "" ]]; then
       echo ""
    fi
    GATEWAY_EUI=$(ip link show $GATEWAY_EUI_NIC | awk '/ether/ {print $2}' | awk -F\: '{print "RAK-"$4$5$6}')
    GATEWAY_EUI=${GATEWAY_EUI^^}
    echo $GATEWAY_EUI
}



if [ ! -d "/opt/ttn-gateway/packet_forwarder" ]; then
    if [ "$GW_MODEL" = "RAK7243" ]; then
        cp /usr/local/rak/lora/rak7243/* /opt/ttn-gateway/ -rf
    elif [ "$GW_MODEL" = "RAK2247" ]; then
        if [ "$LORA_SPI" = "1" ]; then
            cp /usr/local/rak/lora/rak2247_spi/* /opt/ttn-gateway/ -rf
        else
            cp /usr/local/rak/lora/rak2247_usb/* /opt/ttn-gateway/ -rf
        fi
    else
        cp /usr/local/rak/lora/rak2245/* /opt/ttn-gateway/ -rf
    fi
    cp /opt/ttn-gateway/packet_forwarder/lora_pkt_fwd/global_conf/global_conf.eu_863_870.json \
	/opt/ttn-gateway/packet_forwarder/lora_pkt_fwd/global_conf.json

    NEW_HOSTNAME=`do_get_mac`
    CURRENT_HOSTNAME=$(hostname)
    echo $NEW_HOSTNAME > /etc/hostname
    sed -i "s/$CURRENT_HOSTNAME/$NEW_HOSTNAME/" /etc/hosts

fi
